### ISSUE TITLE
Does not like node v8.4.0

### ISSUE THREAD

**Issue by rafgeekee** [ekatzenstein/create-react-app-fullstack#6]
Syntax error when attempting to run `fullstack` command on node v8.4.0

```
.nvm/versions/node/v8.4.0/lib/node_modules/create-react-app-fullstack/index.js:89
        let pkgJson = JSON.parse(packageString)
        ^^^

Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

Which version of node will make this a happy bunny?

**Comment by ghost** [comment]
@rafgeekee I am using node 8.9.1 and to run the `fullstack` command I had use `node ~/.nvm/versions/node/v8.9.1/bin/fullstack`
